# 1. Data collection

In [25]:
import pandas as pd

In [26]:
data = pd.read_csv("rent_apartments.csv")

In [27]:
data

,address,area,constraction_year,rooms,bedrooms,bathrooms,balcony,storage,parking,furnished,garage,garden,energy,facilities,zip,neighborhood,rent
0,1071 HN Amsterdam (Cornelis Schuytbuurt),167.0,1870,3,2,2,yes,no,no,yes,no,Not present,D,Roof terrace,1071 HN,Cornelis Schuytbuurt,4500
1,1071 HK Amsterdam (Concertgebouwbuurt),150.0,1890,3,2,2,yes,no,yes,yes,no,Not present,A,"Cable TV, Internet connection, Fireplace, Bath...",1071 HK,Concertgebouwbuurt,3450
2,1071 HK Amsterdam (Concertgebouwbuurt),150.0,1890,3,2,2,yes,no,yes,yes,no,Not present,A,"Cable TV, Internet connection, Fireplace, Bath...",1071 HK,Concertgebouwbuurt,3450
3,1071 WV Amsterdam (Hondecoeterbuurt),90.0,1923,3,2,1,yes,no,no,yes,no,Not present,None,"Shower, Toilet",1071 WV,Hondecoeterbuurt,2000
4,1071 WV Amsterdam (Hondecoeterbuurt),104.0,1923,3,2,1,no,no,no,no,no,Present (47 m²),D,"Shower, Bath, Toilet",1071 WV,Hondecoeterbuurt,3250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,1033 DL Amsterdam (Terrasdorp),75.0,1990,3,2,1,no,no,no,yes,no,Not present,C,None,1033 DL,Terrasdorp,1450
1724,1033 DZ Amsterdam (Terrasdorp),75.0,1990,3,2,1,yes,no,no,yes,no,Not present,C,Shower,1033 DZ,Terrasdorp,1500
1725,1021 NX Amsterdam (IJplein e.o.),74.0,1986,2,1,1,no,no,no,yes,no,Not present,None,None,1021 NX,IJplein e.o.,1400
1726,1021 EC Amsterdam (Vogelbuurt Zuid),118.0,1920,5,4,1,yes,yes,yes,yes,no,Not present,G,"Storage space, Shower, Toilet",1021 EC,Vogelbuurt Zuid,2650
1727,1042 AL Amsterdam (Westhaven Noord),110.0,2019,5,4,2,no,yes,no,yes,no,Not present,None,"Internet connection, Air-conditioning, Storage...",1042 AL,Westhaven Noord,2600

# 2. Data preparation

In [28]:
data.dtypes

address               object
area                 float64
constraction_year      int64
rooms                  int64
bedrooms               int64
bathrooms              int64
balcony               object
storage               object
parking               object
furnished             object
garage                object
garden                object
energy                object
facilities            object
zip                   object
neighborhood          object
rent                   int64
dtype: object

In [29]:
data_encoded = pd.get_dummies(data, 
                              columns = ['balcony',
                                         'parking', 
                                         'furnished', 
                                         'garage', 
                                         'storage'], 
                              drop_first=True)

In [30]:
data_encoded

,address,area,constraction_year,rooms,bedrooms,bathrooms,garden,energy,facilities,zip,neighborhood,rent,balcony_yes,parking_yes,furnished_yes,garage_yes,storage_yes
0,1071 HN Amsterdam (Cornelis Schuytbuurt),167.0,1870,3,2,2,Not present,D,Roof terrace,1071 HN,Cornelis Schuytbuurt,4500,1,0,1,0,0
1,1071 HK Amsterdam (Concertgebouwbuurt),150.0,1890,3,2,2,Not present,A,"Cable TV, Internet connection, Fireplace, Bath...",1071 HK,Concertgebouwbuurt,3450,1,1,1,0,0
2,1071 HK Amsterdam (Concertgebouwbuurt),150.0,1890,3,2,2,Not present,A,"Cable TV, Internet connection, Fireplace, Bath...",1071 HK,Concertgebouwbuurt,3450,1,1,1,0,0
3,1071 WV Amsterdam (Hondecoeterbuurt),90.0,1923,3,2,1,Not present,None,"Shower, Toilet",1071 WV,Hondecoeterbuurt,2000,1,0,1,0,0
4,1071 WV Amsterdam (Hondecoeterbuurt),104.0,1923,3,2,1,Present (47 m²),D,"Shower, Bath, Toilet",1071 WV,Hondecoeterbuurt,3250,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,1033 DL Amsterdam (Terrasdorp),75.0,1990,3,2,1,Not present,C,None,1033 DL,Terrasdorp,1450,0,0,1,0,0
1724,1033 DZ Amsterdam (Terrasdorp),75.0,1990,3,2,1,Not present,C,Shower,1033 DZ,Terrasdorp,1500,1,0,1,0,0
1725,1021 NX Amsterdam (IJplein e.o.),74.0,1986,2,1,1,Not present,None,None,1021 NX,IJplein e.o.,1400,0,0,1,0,0
1726,1021 EC Amsterdam (Vogelbuurt Zuid),118.0,1920,5,4,1,Not present,G,"Storage space, Shower, Toilet",1021 EC,Vogelbuurt Zuid,2650,1,1,1,0,1
1727,1042 AL Amsterdam (Westhaven Noord),110.0,2019,5,4,2,Not present,None,"Internet connection, Air-conditioning, Storage...",1042 AL,Westhaven Noord,2600,0,0,1,0,1

In [31]:
data_encoded.garden.unique()

array(['Not present', 'Present (47 m²)', 'Present (29 m²)',
       'Present (75 m²)', 'Present (40 m², located on the north)',
       'Present (50 m²)', 'Present (20 m², located on the south)',
       'Present (1 m²)', 'Present (15 m²)', 'Present (25 m²)',
       'Present (12 m²)', 'Present (45 m², located on the south)',
       'Present (26 m², located on the south-east)',
       'Present (20 m², located on the north-east)',
       'Present (42 m², located on the west)', 'Present (46 m²)',
       'Present (45 m², located on the south-west)',
       'Present (60 m², located on the south-west)',
       'Present (50 m², located on the south)',
       'Present (40 m², located on the north-east)', 'Present (16 m²)',
       'Present (60 m²)', 'Present (65 m², located on the south)',
       'Present (90 m²)', 'Present (85 m²)',
       'Present (85 m², located on the south-west)',
       'Present (500 m², located on the west)',
       'Present (45 m², located on the west)',
       'Present (12 m², located on the south)',
       'Present (30 m², located on the north-west)',
       'Present (60 m², located on the south-east)',
       'Present (49 m², located on the east)',
       'Present (51 m², located on the south-east)', 'Present (80 m²)',
       'Present (27 m²)', 'Present (56 m²)', 'Present (65 m²)',
       'Present (20 m²)', 'Present (9 m²)', 'Present (200 m²)',
       'Present (32 m²)', 'Present (45 m²)',
       'Present (100 m², located on the south)', 'Present (34 m²)'],
      dtype=object)

In [32]:
import re

In [33]:
data_encoded.garden[3]

'Not present'

In [34]:
int(re.findall(r'\d+', data_encoded.garden[3])[0])

IndexError: list index out of range

In [35]:
for i in range(len(data_encoded)):
    if data_encoded.garden[i]=='Not present':
        data_encoded.garden[i]=0
    else: data_encoded.garden[i] = int(re.findall(r'\d+', data_encoded.garden[i])[0])

/var/folders/5y/7zvhsc3x5nx162713kvx9c1m0000gn/T/ipykernel_46869/3850921411.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_encoded.garden[i]=0
/var/folders/5y/7zvhsc3x5nx162713kvx9c1m0000gn/T/ipykernel_46869/3850921411.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  else: data_encoded.garden[i] = int(re.findall(r'\d+', data_encoded.garden[i])[0])

In [36]:
data_encoded.garden.unique()

array([0, 47, 29, 75, 40, 50, 20, 1, 15, 25, 12, 45, 26, 42, 46, 60, 16,
       65, 90, 85, 500, 30, 49, 51, 80, 27, 56, 9, 200, 32, 100, 34],
      dtype=object)

# 3. Model Building

## 3.1. Defining X and y

In [37]:
X = data_encoded[['area', 
                  'constraction_year', 
                  'bedrooms', 
                  'garden', 
                  'balcony_yes', 
                  'parking_yes', 
                  'furnished_yes', 
                  'garage_yes', 
                  'storage_yes']]

In [38]:
y = data_encoded.rent

In [39]:
y

0       4500
1       3450
2       3450
3       2000
4       3250
        ...
1723    1450
1724    1500
1725    1400
1726    2650
1727    2600
Name: rent, Length: 1728, dtype: int64

In [40]:
X

,area,constraction_year,bedrooms,garden,balcony_yes,parking_yes,furnished_yes,garage_yes,storage_yes
0,167.0,1870,2,0,1,0,1,0,0
1,150.0,1890,2,0,1,1,1,0,0
2,150.0,1890,2,0,1,1,1,0,0
3,90.0,1923,2,0,1,0,1,0,0
4,104.0,1923,2,47,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
1723,75.0,1990,2,0,0,0,1,0,0
1724,75.0,1990,2,0,1,0,1,0,0
1725,74.0,1986,1,0,0,0,1,0,0
1726,118.0,1920,4,0,1,1,1,0,1
1727,110.0,2019,4,0,0,0,1,0,1

## 3.2. Split the dataset

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## 3.3. Model Building

In [43]:
from sklearn.ensemble import RandomForestRegressor

In [44]:
rf = RandomForestRegressor()

In [45]:
rf.fit(X_train, y_train)

RandomForestRegressor()

## 3.4. Evaluate Model

In [145]:
rf.score(X_test, y_test)

0.5430670976676156

## 3.5. Predicting

In [146]:
X

,area,constraction_year,bedrooms,garden,balcony_yes,parking_yes,furnished_yes,garage_yes,storage_yes
0,167.0,1870,2,0,1,0,1,0,0
1,150.0,1890,2,0,1,1,1,0,0
2,150.0,1890,2,0,1,1,1,0,0
3,90.0,1923,2,0,1,0,1,0,0
4,104.0,1923,2,47,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
1723,75.0,1990,2,0,0,0,1,0,0
1724,75.0,1990,2,0,1,0,1,0,0
1725,74.0,1986,1,0,0,0,1,0,0
1726,118.0,1920,4,0,1,1,1,0,1
1727,110.0,2019,4,0,0,0,1,0,1

In [147]:
rf.predict([[85, 2015, 2, 20, 1, 1, 0, 0, 1]])

/Users/andrewwolf/.pyenv/versions/3.10.7/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([1903.60033333])

## 3.6. Tuning Hyperparameters

In [47]:
from sklearn.model_selection import GridSearchCV

In [48]:
grid_space = {'n_estimators': [100, 200, 300], 'max_depth': [3, 6, 9, 12]}

In [49]:
grid = GridSearchCV(RandomForestRegressor(), param_grid=grid_space, cv=5, scoring = 'r2')

In [50]:
model_grid = grid.fit(X_train, y_train)

In [51]:
print(f'Best hyperparameters are {model_grid.best_params_}, score = {model_grid.best_score_}')

Best hyperparameters are {'max_depth': 12, 'n_estimators': 100}, score = 0.732347841612605

In [53]:
model_grid.best_estimator_.predict([[85, 2015, 2, 20, 1, 1, 0, 0, 1]])

/Users/andrewwolf/.pyenv/versions/3.10.7/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([1939.50041667])

# 4. Models Management

In [169]:
import pickle as pk

In [170]:
pk.dump(rf, open('models/rf_v1', 'wb'))

In [172]:
!ls models/

rf_v1

In [178]:
rf_v1 = pk.load(open('models/rf_v1', 'rb'))

In [179]:
rf_v1.predict([[85, 2015, 2, 20, 1, 1, 0, 0, 1]])

/Users/andrewwolf/.pyenv/versions/3.10.7/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([1984.13478277])